[project]
name = "rag-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veera", email = "veerababu.narni@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-google-genai>=4.3.2",
    "python-dotenv>=1.2.2",
]

[project.scripts]
rag-basic = "rag_basic:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
